### ISSUE TITLE
Tracking: Tweak places queries

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#158]
These are the final specs (for MVP) for queries we need:

Redux data model
* `TopSites`
* `FrecentLinks`
* `RecentLinks`

APIs
* [x] All-time top frecent, goes to `TopSites` in redux store, used in `TopSites` component on the new tab page
* [x] #164: Top frecent *urls* (not sites) in the last 72 hours. Site data should include whether or not the frecent link was bookmarked at some point. Bookmarks should be prioritized first, and the top 10 items should be returned, finally sorted by `date_visited`. Results go to `FrecentLinks` in redux store, used in both `Spotlight` and `ActivityFeed` on the new tab page.
* [x] #165: Recent *urls* limited by 25. Site data should include whether or not the link was bookmarked. This will eventually need to be paginated.
* [x] Recent Bookmarks: We don't actually need this on its own, but let's keep it anyway for now incase we want it later. 

Notes
* Items in the `TopSites`, `Spotlight`, and `ActivityFeed` components on the new tab page should be deduped based on URL. i.e. if a site is shown in Top Sites, it should never show up in Spotlight; if a url is shown in Spotlight, it should not be shown in the `ActivityFeed` on that page. 
* The `Spotlight` component should use `FrecentLinks`. Items should all have a title, image, and description. The title and description should not be equal. 2/3 items should be bookmarks if they exist.

**Comment by oyiptong** [comment]
Looks like there is one new query, and one tweak.

## Time-constrained top frecent links

New API:

What we want now is the top frecent links, with the constraint that the links need to have a maximum age for consideration.

What do we consider this age? Probably `last_visit_date` in `moz_places` as a discrimination criterion.

## Add bookmark Guid and Id to top recent links

This is a tweak.

We probably want to track those separately

**Comment by oyiptong** [comment]
Also, while this is set to the Alpha milestone, this may need to get into Beta due to time constraints

**Comment by oyiptong** [comment]
This also needs corresponding UI issues for tracking

**Comment by k88hudson** [comment]
Just a heads up @nchapman @bryanbell, this will not be implemented until the Beta milestone, so the data sources won't be exactly right for the end of this milestone/when we first release for internal testing.

**Comment by nchapman** [comment]
> the data sources won't be exactly right for the end of this milestone/when we first release for internal testing.

No problem. We'll put this in the release notes.

**Comment by oyiptong** [comment]
closing, because this is done

**Comment by tspurway** [comment]
@k88hudson need to implement new frecent query
