### ISSUE TITLE
Tracking ticket: style polish

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#482]
Filing this to keep track of all the [style polish](https://github.com/mozilla/activity-streams/labels/Polish) tickets

* [x] #386 ~~Top sites borders are covered by title background~~ (merged -- #508)
* [x] #396 ~~Margins, colors, font sizes~~ (merged -- #511)
* [x] #398 Add date divider heads to Timeline
* [x] #458 ~~See more / link to timeline is confusing~~ (merged -- #512)
* [x] #489 ~~Fallback icons aren't square~~ (merged -- #511)
* [x] #498 ~~Highlight boxes are different sizes~~ (merged -- #511)
* [x] #502 ~~Long titles have a bit of overflow on highlights~~ (merged -- #511)

**Comment by pdehaan** [comment]
:sparkles: Added [Polish](https://github.com/mozilla/activity-streams/labels/Polish) tags :sparkles:
